preview-kits-menu:
  previous-page-button:
    material: 'PLAYER_HEAD:http://textures.minecraft.net/texture/816ea34a6a6ec5c051e6932f1c471b7012b298d38d179f1b487c413f51959cd4'
    name: '<bold><color:yellow>(!)<color:yellow></bold> <gradient:yellow:gold>Preview previous level!</gradient>'
    glow: false
    lore: []
  no-previous-page-button:
    material: 'PLAYER_HEAD:http://textures.minecraft.net/texture/3ed1aba73f639f4bc42bd48196c715197be2712c3b962c97ebf9e9ed8efa025'
    name: '<bold><color:red>(!)<color:red></bold> <gradient:red:dark_red>No previous level!</gradient>'
    glow: false
    lore:
      - '&7You have reached the first level of this kit.'
  next-page-button:
    material: 'PLAYER_HEAD:http://textures.minecraft.net/texture/9c9ec71c1068ec6e03d2c9287f9da9193639f3a635e2fbd5d87c2fabe6499'
    name: '<bold><color:yellow>(!)<color:yellow></bold> <gradient:yellow:gold>Preview next level!</gradient>'
    glow: false
    lore: []
  no-next-page-button:
    material: 'PLAYER_HEAD:http://textures.minecraft.net/texture/3ed1aba73f639f4bc42bd48196c715197be2712c3b962c97ebf9e9ed8efa025'
    name: '<bold><color:red>(!)<color:red></bold> <gradient:red:dark_red>No next level!</gradient>'
    glow: false
    lore:
      - '&7You have reached the last level of this kit.'
  no-upgrade-button:
    material: 'BARRIER'
    name: '<bold><color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727> <gradient:#D22727:#F26F0F>Upgrade {kit}</gradient> <color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Upgrade to level:</gradient> <bold><color:yellow>{upgrade_level}<color:yellow></bold>'
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Cost:</gradient> <color:#E5DCD9>FREE<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#D22727:#F26F0F>(( This kit has no available upgrades! ))</gradient></italic>'
  default-level-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727> <gradient:#D22727:#F26F0F>Upgrade {kit}</gradient> <color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Upgrade to level:</gradient> <bold><color:yellow>{upgrade_level}<color:yellow></bold>'
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Cost:</gradient> <color:#E5DCD9>FREE<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#D22727:#F26F0F>(( This is the default kit level! ))</gradient></italic>'
  available-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A> <gradient:#10987A:#49ECC3>Upgrade {kit}</gradient> <color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit level:</gradient> <bold><underlined><color:yellow>{upgrade_level}<color:yellow></underlined></bold> <bold><color:gray>/<color:gray></bold> <bold><underlined><color:red>{maximum_level}<color:red></underlined></bold>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Cost:</gradient> <color:red>{cost}<color:red>'
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit cooldown:</gradient> <color:#E5DCD9>{total}<color:#E5DCD9>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Number of Items:</gradient> <color:#E5DCD9>{items}<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#10987A:#49ECC3>(( Click to buy this upgrade! ))</gradient></italic>'
  insufficient-funds-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727> <gradient:#D22727:#F26F0F>Upgrade {kit}</gradient> <color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Upgrade to level:</gradient> <bold><color:yellow>{upgrade_level}<color:yellow></bold>'
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Cost:</gradient> <color:#E5DCD9>{cost}<color:#E5DCD9> &7&o(Needed {needed})'
      - ''
      - '<italic><gradient:#D22727:#F26F0F>(( You cannot afford this kit upgrade! ))</gradient></italic>'
  locked-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727> <gradient:#D22727:#F26F0F>Upgrade {kit}</gradient> <color:#D22727>✧<color:#D22727><color:#F26F0F>✦<color:#F26F0F><color:#D22727>✧<color:#D22727></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Upgrade to level:</gradient> <bold><color:yellow>{upgrade_level}<color:yellow></bold>'
      - ' <bold><color:#D22727>*<color:#D22727></bold> <gradient:#D22727:#F26F0F>Cost:</gradient> <color:#E5DCD9>{cost}<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#D22727:#F26F0F>(( You must to unlock this kit first! ))</gradient></italic>'
  maximum-level-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#DACB1C>✧<color:#DACB1C><color:#CBF91B>✦<color:#CBF91B><color:#DACB1C>✧<color:#DACB1C> <gradient:#DACB1C:#CBF91B>Upgrade {kit}</gradient> <color:#DACB1C>✧<color:#DACB1C><color:#CBF91B>✦<color:#CBF91B><color:#DACB1C>✧<color:#DACB1C></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#DACB1C>*<color:#DACB1C></bold> <gradient:#DACB1C:#CBF91B>Upgrade to level:</gradient> <bold><color:yellow>{upgrade_level}<color:yellow></bold>'
      - ' <bold><color:#DACB1C>*<color:#DACB1C></bold> <gradient:#DACB1C:#CBF91B>Cost:</gradient> <color:#E5DCD9>{cost}<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#DACB1C:#CBF91B>(( You have reached the maximum level! ))</gradient></italic>'
  unavailable-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#DACB1C>✧<color:#DACB1C><color:#CBF91B>✦<color:#CBF91B><color:#DACB1C>✧<color:#DACB1C> <gradient:#DACB1C:#CBF91B>Upgrade {kit}</gradient> <color:#DACB1C>✧<color:#DACB1C><color:#CBF91B>✦<color:#CBF91B><color:#DACB1C>✧<color:#DACB1C></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#DACB1C>*<color:#DACB1C></bold> <gradient:#DACB1C:#CBF91B>Upgrade to level:</gradient> <bold><color:yellow>{upgrade_level}<color:yellow></bold>'
      - ' <bold><color:#DACB1C>*<color:#DACB1C></bold> <gradient:#DACB1C:#CBF91B>Cost:</gradient> <color:#E5DCD9>{cost}<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#DACB1C:#CBF91B>(( Unlock the previous upgrades first! ))</gradient></italic>'
  complete-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A> <gradient:#10987A:#49ECC3>Upgrade {kit}</gradient> <color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit level:</gradient> <bold><underlined><color:yellow>{upgrade_level}<color:yellow></underlined></bold> <bold><color:gray>/<color:gray></bold> <bold><underlined><color:red>{maximum_level}<color:red></underlined></bold>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Cost:</gradient> <color:red><strikethrough>{cost}</strikethrough><color:red>'
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit cooldown:</gradient> <color:#E5DCD9>{total}<color:#E5DCD9>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Number of Items:</gradient> <color:#E5DCD9>{items}<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#10987A:#49ECC3>(( You already bought this upgrade! ))</gradient></italic>'
  current-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A> <gradient:#10987A:#49ECC3>Upgrade {kit}</gradient> <color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit level:</gradient> <bold><underlined><color:yellow>{upgrade_level}<color:yellow></underlined></bold> <bold><color:gray>/<color:gray></bold> <bold><underlined><color:red>{maximum_level}<color:red></underlined></bold>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Cost:</gradient> <color:red><strikethrough>{cost}</strikethrough><color:red>'
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit cooldown:</gradient> <color:#E5DCD9>{total}<color:#E5DCD9>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Number of Items:</gradient> <color:#E5DCD9>{items}<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#10987A:#49ECC3>(( This is your current upgrade! ))</gradient></italic>'
  delay-upgrade-button:
    material: 'PLAYER_HEAD:https://textures.minecraft.net/texture/71bdf5e4225d6683c393d6f8b2b735ed228eb6f3a078d0d791adeca55e4392fa'
    name: '<bold><color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A> <gradient:#10987A:#49ECC3>Upgrade {kit}</gradient> <color:#10987A>✧<color:#10987A><color:#49ECC3>✦<color:#49ECC3><color:#10987A>✧<color:#10987A></bold>'
    glow: false
    lore:
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit level:</gradient> <bold><underlined><color:yellow>{upgrade_level}<color:yellow></underlined></bold> <bold><color:gray>/<color:gray></bold> <bold><underlined><color:red>{maximum_level}<color:red></underlined></bold>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Cost:</gradient> <color:red><strikethrough>{cost}</strikethrough><color:red>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Buy delay:</gradient> <color:#E5DCD9>{buy_delay_remaining} / {buy_delay}<color:#E5DCD9>'
      - ''
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Kit cooldown:</gradient> <color:#E5DCD9>{total}<color:#E5DCD9>'
      - ' <bold><color:#10987A>*<color:#10987A></bold> <gradient:#10987A:#49ECC3>Number of Items:</gradient> <color:#E5DCD9>{items}<color:#E5DCD9>'
      - ''
      - '<italic><gradient:#10987A:#49ECC3>(( You have to wait for the delay! ))</gradient></italic>'
open-menu-commands:
  - 'kits;advancedkits.command.kits'
claim-kit-commands:
  - 'kit;advancedkits.command.kit'
kit-preview-commands:
  - 'kitpreview;advancedkits.command.kitpreview'
first-join-vouchers: []
first-join-kits:
  - 'Coal;1'
close-kits-menu-before-opening-preview-menu: true
data-save-interval-ticks: 12000
cost-formatting:
  exp: '{amount} EXP'
  vault: '${amount}'
placeholders:
  unlimited-kit-usages: 'Unlimited'
time-units:
  finish: 'Now'
  years: '{number} Years '
  year: '{number} Year '
  no-years: ''
  months: '{number} Months '
  month: '{number} Month '
  no-months: ''
  weeks: '{number} Weeks '
  week: '{number} Week '
  no-weeks: ''
  days: '{number} Days '
  day: '{number} Day '
  no-days: ''
  hours: '{number} Hours '
  hour: '{number} Hour '
  no-hours: ''
  minutes: '{number} Minutes '
  minute: '{number} Minute '
  no-minutes: ''
  seconds: '{number} Seconds'
  second: '{number} Second'
  no-seconds: ''
permissions:
  main-command: 'advancedkits.command.use'
main-command-aliases:
  - ak
