name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: ${project.description}
website: ${url}
api-version: 1.13
load: POSTWORLD
authors:
  - extremall
softdepend:
  - PlaceholderAPI
  - Vault